apiVersion: apps/v1
kind: Deployment
metadata:
  name: bgame-deployment
spec:
  selector:
    matchLabels:
      app: bgame
  replicas: 2
  template:
    metadata:
      labels:
        app: bgame
    spec:
      containers:
        - name: bgame
          image: nelsonosagie/bgame:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080


---

apiVersion: v1
kind: Service
metadata:
  name: bgame-svc
spec:
  selector:
    app: bgame
  ports:
    - protocol: "TCP"
      port: 80
      targetPort: 8080 
  type: LoadBalancer
